name: Build Static Git for Android (aarch64)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  # 指定 Git 版本
  GIT_VERSION: 2.50.0
  # 目标 Android API level（最低支持）
  ANDROID_API: 21
  # NDK 版本，可以根据需要换成 r25c、r26b 等
  NDK_VERSION: r25c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Android NDK
        run: |
          NDK_ZIP="android-ndk-${NDK_VERSION}-linux.zip"
          curl --fail -L "https://dl.google.com/android/repository/${NDK_ZIP}" -o "${NDK_ZIP}"
          unzip -q "${NDK_ZIP}"
          mv "android-ndk-${NDK_VERSION}" "$HOME/android-ndk"

      - name: Set up environment
        run: |
          export ANDROID_NDK=$HOME/android-ndk
          # 交叉编译目标三元组
          export TARGET=aarch64-linux-android
          # 指定 Clang 前缀
          export CC="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET}${ANDROID_API}-clang"
          export CXX="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET}${ANDROID_API}-clang++"
          export AR="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
          export RANLIB="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
          export LD="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld"
          export SYSROOT="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot"

          # 确认工具链可用
          echo "CC = $CC"
          "$CC" --version

      - name: Build Git ${GIT_VERSION}
        run: |
          # 进入临时编译目录
          mkdir -p build-git && cd build-git

          # 下载源码
          wget -q "https://www.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.gz"
          tar xf "git-${GIT_VERSION}.tar.gz"
          cd "git-${GIT_VERSION}"

          # 生成 configure
          make configure

          # 配置静态编译
          ./configure \
            --host=${TARGET} \
            --prefix=/src/output \
            --with-openssl \
            --without-tcltk \
            CFLAGS="--sysroot=${SYSROOT} -O2 -fPIE -static" \
            LDFLAGS="--sysroot=${SYSROOT} -static -fuse-ld=lld" \
            NO_GETTEXT=YesPlease \
            NO_TCLTK=YesPlease

          # 并行编译与安装
          make -j"$(nproc)"
          make install

          # 精简可执行文件
          $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip /src/output/bin/git*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-android-aarch64
          path: output/bin/
