name: Build Static Git for Android (arm64)

on:
  workflow_dispatch:

jobs:
  build-git-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
          curl unzip pkg-config python3 python3-pip bzip2
        
    - name: Set up NDK
      run: |
        NDK_VERSION=r25c
        curl -Lo android-ndk.zip https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
        unzip -q android-ndk.zip
        rm android-ndk.zip
        echo "NDK_HOME=$(pwd)/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
        echo "TOOLCHAIN=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

    - name: Build Git for arm64
      run: |
        chmod +x ./build-static-git.sh
        ./build-static-git.sh aarch64-linux-android 24

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: git-android-arm64
        path: |
          git-aarch64-linux-android/git
          git-aarch64-linux-android/git-*.tar.gz
