name: Build Static Git for Android

on:
  workflow_dispatch:

jobs:
  build-git-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm, arm64, x86, x86_64]
        include:
          - arch: arm
            target: arm-linux-androideabi
            api: 24
          - arch: arm64
            target: aarch64-linux-android
            api: 24
          - arch: x86
            target: i686-linux-android
            api: 24
          - arch: x86_64
            target: x86_64-linux-android
            api: 24

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
          curl unzip pkg-config python3 python3-pip
        
    - name: Set up NDK
      run: |
        NDK_VERSION=r25c
        curl -Lo android-ndk.zip https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
        unzip -q android-ndk.zip
        rm android-ndk.zip
        echo "NDK_HOME=$(pwd)/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
        echo "TOOLCHAIN=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

    - name: Build Git
      run: |
        chmod +x ./build-static-git.sh
        ./build-static-git.sh ${{ matrix.target }} ${{ matrix.api }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-android-${{ matrix.arch }}
        path: |
          git-${{ matrix.target }}/git
          git-${{ matrix.target }}/git-*.tar.gz
