name: Build Static Git for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t git-android-builder -f Dockerfile-git.android .

    - name: Extract Binary
      run: |
        # 清理可能的旧容器
        docker ps -aq | xargs -r docker rm -f &>/dev/null || true
        
        # 创建临时容器并复制二进制文件
        docker create --name temp-container git-android-builder
        docker cp temp-container:/app/git ./git
        docker rm -f temp-container

        # 验证文件
        if [ ! -f ./git ]; then
          echo "错误：文件提取失败！"
          exit 1
        fi
        
        # 显示文件信息
        file ./git
        ls -lh ./git
        
        # 重命名文件
        mv ./git ./git-android-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-android-arm64
        path: ./git-android-arm64
        retention-days: 7
