# .github/workflows/build-git-static.yml
name: Build Static Git

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build static Git in Alpine container
        run: |
          # 在 Alpine 容器中安装编译依赖并静态编译 Git
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            alpine:3.18 \
            sh -eux -c '
              # 安装 build-base、musl/glibc headers、OpenSSL/CURL/Expat 开发包
              apk add --no-cache \
                build-base \
                musl-dev \
                linux-headers \
                openssl-dev \
                curl-dev \
                expat-dev \
                perl-doc \
                asciidoc \
                xmlto \
                docbook2x

              # 下载并解压 Git 源码（可根据需要修改版本号）
              GIT_VERSION=2.50.0
              wget -q "https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.gz"
              tar xf "git-${GIT_VERSION}.tar.gz"
              cd "git-${GIT_VERSION}"

              # 生成 configure 并配置静态编译
              make configure
              ./configure \
                --prefix=/src/output \
                --without-tcltk \
                CFLAGS="-static -Os" \
                LDFLAGS="-static" \
                NO_GETTEXT=YesPlease

              # 编译并安装到 /src/output
              make -j"$(nproc)"
              make install

              # 精简可执行文件
              strip /src/output/bin/git*
            '

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v3
        with:
          name: git-static
          path: output/bin/

