name: Android Static Build

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.android

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        context: .
        tags: termux-tools-builder:latest
        load: true

    - name: Extract Binaries
      run: |
        mkdir -p release
        container_id=$(docker create termux-tools-builder:latest)
        docker cp $container_id:/app/ release/
        docker rm -f $container_id
        ls -lh release/app/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: termux-static-tools-v4
        path: release/app/*
        retention-days: 3
