name: Build Static Echo for Termux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip make gcc g++ musl-tools

    - name: Download Android NDK r28
      run: wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip

    - name: Extract Android NDK
      run: unzip -q android-ndk-r28-linux.zip -d $HOME/android-ndk

    - name: Set NDK Environment Variable
      run: echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r28" >> $GITHUB_ENV

    - name: Download Coreutils
      run: |
        COREUTILS_VERSION=9.4
        wget https://ftp.gnu.org/gnu/coreutils/coreutils-${COREUTILS_VERSION}.tar.xz
        tar xJf coreutils-${COREUTILS_VERSION}.tar.xz

    - name: Build Coreutils (including echo)
      run: |
        COREUTILS_VERSION=9.4
        cd coreutils-${COREUTILS_VERSION}
        CC=musl-gcc ./configure \
          --host=aarch64-linux-android \
          --prefix=$HOME/output \
          --enable-static \
          --disable-nls
        make -j$(nproc) CC=musl-gcc
        make install

    - name: Check Binary
      run: |
        file $HOME/output/bin/echo
        ldd $HOME/output/bin/echo || echo "Static binary confirmed"
        # 预期输出：ELF 64-bit LSB executable... statically linked
        # ldd should fail for static binaries

 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: echo-static-arm64
        path: /home/runner/output/bin/echo
