name: Build Static Echo for Termux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip make

    - name: Download Android NDK r28
      run: wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
    - name: Extract Android NDK
      run: unzip -q android-ndk-r28-linux.zip -d $HOME/android-ndk

    - name: Set NDK Environment Variable
      run: echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r28" >> $GITHUB_ENV

    - name: Build echo
      run: |
        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          --target=aarch64-linux-android21 \
          --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          -static -O2 -o echo src/echo.c

    - name: Check Binary
      run: |
        file echo
        # 预期输出：ELF 64-bit LSB executable... statically linked

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: echo-static-arm64
        path: echo
