name: Build Android Utils

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.android
        push: false
        load: true
        tags: android-utils:latest

    - name: Copy binaries from container
      run: |
        id=$(docker create android-utils:latest)
        mkdir -p build
        docker cp $id:/app/bash ./build/
        docker cp $id:/app/grep ./build/
        docker cp $id:/app/wget ./build/
        docker cp $id:/app/jq ./build/
        docker cp $id:/app/tar ./build/
        docker rm $id

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-utils
        path: build/
        
    - name: Debug Info
      run: |
        docker run --rm termux-tools-builder:latest nm /app/bash-static | grep -i strtoimax
        docker run --rm termux-tools-builder:latest readelf -s /app/bash-static | grep -i strtoimax
