name: Android Static Build

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.android

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Export
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        tags: termux-tools:v4
        outputs: type=docker,dest=./termux-tools.tar

    - name: Extract Binaries
      run: |
        mkdir -p release
        docker load < ./termux-tools.tar
        container_id=$(docker create termux-tools:v4)
        docker cp $container_id:/termux-tools/ release/
        docker rm -f $container_id

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: termux-static-tools
        path: ./release/termux-tools/
        retention-days: 7
