name: Build Static Echo for Termux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip make gcc musl-tools

    - name: Download Android NDK r28
      run: wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip

    - name: Extract Android NDK
      run: unzip -q android-ndk-r28-linux.zip -d $HOME/android-ndk

    - name: Set NDK Environment Variable
      run: |
        echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r28" >> $GITHUB_ENV
        echo "PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Download Coreutils
      run: |
        COREUTILS_VERSION=9.4
        wget https://ftp.gnu.org/gnu/coreutils/coreutils-${COREUTILS_VERSION}.tar.xz
        tar xJf coreutils-${COREUTILS_VERSION}.tar.xz

    - name: Build Coreutils (including echo)
      run: |
        COREUTILS_VERSION=9.4
        cd coreutils-${COREUTILS_VERSION}
        cat <<EOF > missing_functions.h
        #ifndef MISSING_FUNCTIONS_H
        #define MISSING_FUNCTIONS_H
        #include <time.h>
        #include <stdlib.h>
        typedef struct timezone *timezone_t;
        timezone_t tzalloc(const char *name) {
          return NULL;
        }
        void tzfree(timezone_t tz) {}
        time_t mktime_z(timezone_t tz, struct tm *tm) {
          return mktime(tm);
        }
        #endif
        EOF
        CFLAGS="-include $(pwd)/missing_functions.h" ./configure \
          CC="aarch64-linux-android21-clang" \
          --host=aarch64-linux-android \
          --prefix=$HOME/output \
          --disable-nls
        make -j$(nproc) CC="aarch64-linux-android21-clang"
        make install

    - name: Check Binary
      run: |
        file $HOME/output/bin/echo
        ldd $HOME/output/bin/echo || echo "Static binary confirmed"
        # 预期输出：ELF 64-bit LSB executable... statically linked
        # ldd should fail for static binaries

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: echo-static-arm64
        path: $HOME/output/bin/echo
