name: Build Static Grep for Termux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip make tar

    - name: Download Android NDK r28
      run: wget https://dl.google.com/android/repository/android-ndk-r28b-linux-x86_64.zip

    - name: Extract Android NDK
      run: unzip -q android-ndk-r28b-linux-x86_64.zip -d $HOME/android-ndk

    - name: Set NDK Environment Variable
      run: echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r28b" >> $GITHUB_ENV

    - name: Download GNU Grep Source
      run: wget https://ftp.gnu.org/gnu/grep/grep-3.8.tar.xz

    - name: Extract GNU Grep Source
      run: tar -xf grep-3.8.tar.xz

    - name: Configure and Build Grep
      run: |
        cd grep-3.8
        # 设置交叉编译器为 NDK 中的 clang
        export CC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
        # 设置编译参数：指定目标平台、sysroot 和静态链接优化选项
        export CFLAGS="--target=aarch64-linux-android21 --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot -static -Os"
        export LDFLAGS="-static"
        # 关闭本地化支持以简化编译（可根据需要调整）
        ./configure --host=aarch64-linux-android --disable-nls
        make -j$(nproc)

    - name: Check Binary
      run: |
        # 检查生成的 grep 可执行文件是否为静态链接的 ELF 文件
        file grep-3.8/src/grep
        # 预期输出类似：ELF 64-bit LSB executable, statically linked,...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: grep-static-arm64
        path: grep-3.8/src/grep
