name: Build Static Bash for ZeroTermux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu make wget

    - name: Download Bash Source
      run: wget https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz

    - name: Extract Source
      run: tar -xzf bash-5.2.tar.gz

    - name: Configure and Build
      run: |
        cd bash-5.2
        CC=aarch64-linux-gnu-gcc ./configure \
          --host=aarch64-linux-gnu \
          --enable-static-link \
          --without-bash-malloc \
          --without-readline \
          CFLAGS="-static -Os" \
          LDFLAGS="-static"
        make -j$(nproc)

    - name: Check Binary
      run: |
        file bash-5.2/bash
        # 预期输出：ELF 64-bit LSB executable... statically linked

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bash-static-arm64
        path: bash-5.2/bash
